language: node_js
node_js:
- '8'
addons:
  code_climate:
    repo_token:
      secure: cNDA5Ks2oXqR8QTegimFuSHeNt52gSiZ1cUfMD+SMY1j0On47HAD7bS3C1Zax0SD/0kgSRd2ccwSegNcMlvVyurlMqjdcxGTep4+KhP0SYUXOEN6EBwebVUOWJbzHMHZmO6FSz//cNvt7o19taqF6qKNsdYTrRCHTVkPXe6q9iPA6NQoDex+f5aX1BRqIXe08bTzoFTfNKEBIcYUqBZNujK9mxFqhgOiW7tTZU2l6DVmWwOF45CWoWX3FJa9XlQKdSY7Lf9Y4BWVLu4Gxi+0WfYAaCervb81gy+Bgv8Udh5ZOqIoTy/F82a/0E5T/4x8YpLLJsPi4yGEQ5VwnUzmAItWYD3jx37Gh7cJ1OtPzcXXB2xBox++pFK8Vzsj1WrNsIQ9o69TF9zW3lagcn0QsMQaLgYto5f1e6RPRZWgh+KZRJFQVEUJCiWXWnn1I4P9XODM6drXZRRwmNU5B/8/dS1tZ1N6YeLNSjVfVK4GMp6x17baM6W8OX+jH5dbzvaFOIVtAbg9DOOsqo7Us7viMbn9wTkkjXxmRy/Eu7xhtNOIE1LagpZ8q09LTk0+RyriovK3zJqu4x7MHqw4mq66UgpVaEIkft3fwE48rmFfIx/hggg7byvJBfO+nOQmjW7im9IllnktIGSR0cUbJblhoPxs3tVZPgGMgsZhlhOOy1k=
script: ./node_modules/.bin/nyc --reporter=lcov yarn test
before_script:
- npm install codeclimate-test-reporter nyc -g
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
cache: yarn
    
